module.exports = {
  content: "content/**/*",
  contentPages: "./*.md",
  contentPosts: "posts/*.md",
  portfolioItems: "portfolio/*.md",
  templates: "templates/**/*",
  helpers: "helpers/**/*.js",
  layoutsFolder: "templates/layouts",
  partialsFolder: "templates/partials",
  assetsFolder: "assets",
  assetsImages: "assets/images/**/*",
  scssEntry: "assets/scss/main.scss",
  scssFolder: "assets/scss/**/*",
  jsEntries: "./assets/js/*.js",
  jsFolder: "assets/js/**/*.js",
  fontsFolder: "assets/fonts/**",
  outputFolder: "./dist",
  outputImagesFolder: "./dist/assets/images",
  outputCssFolder: "./dist/assets/css",
  outputFontsFolder: "./dist/assets/fonts",
  generators: "*.js"
}
