name: Deploy and build static site

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set datetime env var
      run: echo "DATETIME=$(date -u +"%Y%m%d-%H%M%SZ")" >> $GITHUB_ENV
    - name: Set deploy folder env var
      run: echo "TMP_FOLDER=/tmp/${{github.event.repository.name}}-${{env.DATETIME}}" >> $GITHUB_ENV
    - name: Test env var names
      run: |
        echo $DATETIME
        echo $TMP_FOLDER
    - uses: actions/checkout@v1
    - name: build
      uses: TartanLlama/actions-eleventy@master
      with:
        install_dependencies: true
    - name: transfer
      uses: appleboy/scp-action@master
      with:
        source: "dist"
        target: "${{env.TMP_FOLDER}}"
        strip_components: 1
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
    - name: Testing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          mv ${{env.TMP_FOLDER}} ${{ secrets.DEPLOY_FOLDER }}
          cd ${{ secrets.DEPLOY_FOLDER }}
          ls -al