name: Deploy and build static site

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set env
      run: echo "DATETIME=$(date -u +"%Y-%m-%dT%H:%M:%SZ")" >> $GITHUB_ENV
    - name: Test
      run: echo $DATETIME
    - uses: actions/checkout@v1
    - name: build
      uses: TartanLlama/actions-eleventy@master
      with:
        install_dependencies: true
    - name: transfer
      uses: appleboy/scp-action@master
      with:
        source: "dist"
        target: "${{format('{0}{1}', '/tmp/', github.event.repository.name )}}"
        strip_components: 1
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
    - name: Testing remote command
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd /var/www/jegtnes
          ls -al